name: myFirstGithubActions
env:
  APP_NAME: "React App"
  VERSION: "React deploy ver ${{ github.sha }}"
on:
  push:
    branches:
      - main
jobs:
  my_test:
      runs-on: ubuntu-latest
      
      steps:
      - name: Print text test
        run: echo "Hello test"
        run: echo "App name - ${{ env.APP_NAME }}"
        
  my_deploy:
      runs-on: ubuntu-latest
      needs: [my_test]
      steps:
      - name: Print text deploy
        run: echo "Hello deploy"      
